
#type: args

train:
  epochs: 30
  batch_size: 8
  lr: 5.0e-4
  itr_per_epoch: 1.0e+8

diffusion:
  layers: 4
  channels: 256
  nheads: 8
  diffusion_embedding_dim: 256
  beta_start: 0.0001
  beta_end: 0.8
  num_steps: 250
  schedule: "quad"
  is_linear: False
  noise_esti: False
  cfg: True
  c_mask_prob: 0.65
  ddim: True
  sample_steps: 50
  sample_method: "quad"
  pre_norm: False

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "test"
  num_sample_features: 64
  timestep_branch: False
  timestep_emb_cat: True
  with_texts: True
  relative_size_emb_cat: False
  decomp: False
  llm: "bert"
  llm_layers: 0
